version: '3'

services: 
  db:
    image: 'postgres'
    environment: 
      POSTGRES_PASSWORD: '12345'
      POSTGRES_USER: 'docker'
    volumes: 
      - data:/var/lib/postgresql/data
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
  backend:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    image: kickd/mybackend:docker
    volumes:
      - /opt/app/node_modules
      - ./backend:/opt/app
    environment: 
      POSTGRES_PASSWORD: '12345'
      POSTGRES_USER: 'docker'
      CHOKIDAR_USEPOOLING: 'true'
    ports: 
      - '5000:4000'
  frontend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./frontend
    image: kickd/myfrontend:docker
    volumes:
      - /opt/app/node_modules
      - ./frontend:/opt/app
    tty: true
  mynginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./mynginx
    ports: 
      - '9090:80'

volumes:
  data: